# Table of Contents
 <p>

In [30]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import normalize
import numpy as np
import keras

In [2]:
data = load_boston()
print(data['DESCR'])
print(data.keys())
print(data['feature_names'])
print(data['data'].shape)
X = data['data'][:, [5, 6, 7, 9]]
print(X)
y = data['target']
print(y)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [47]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(units=2, activation='sigmoid', input_dim=X.shape[1]))
model.add(keras.layers.Dense(units=1))
model.compile(loss='mean_squared_error',
              optimizer='sgd',)


In [48]:
X_norm = normalize(X, axis=0)
model.fit(X_norm, y, epochs=100, batch_size=32)

Epoch 1/100
506/506 [==============================] - 0s 173us/step - loss: 362.5504
Epoch 2/100
506/506 [==============================] - 0s 25us/step - loss: 133.0282
Epoch 3/100
506/506 [==============================] - 0s 26us/step - loss: 91.4908
Epoch 4/100
506/506 [==============================] - 0s 23us/step - loss: 85.4478
Epoch 5/100
506/506 [==============================] - 0s 27us/step - loss: 84.5502
Epoch 6/100
506/506 [==============================] - 0s 29us/step - loss: 84.4875
Epoch 7/100
506/506 [==============================] - 0s 28us/step - loss: 84.4668
Epoch 8/100
506/506 [==============================] - 0s 29us/step - loss: 84.3981
Epoch 9/100
506/506 [==============================] - 0s 27us/step - loss: 84.4959
Epoch 10/100
506/506 [==============================] - 0s 27us/step - loss: 84.4596
Epoch 11/100
506/506 [==============================] - 0s 28us/step - loss: 84.5359
Epoch 12/100
506/506 [==============================] - 0s 28us/step - 

In [49]:
model.get_weights()

[array([[ 1.11671317,  1.57219398],
        [ 0.07076877, -0.96600294],
        [ 1.58701885,  1.09398055],
        [-0.92230326, -1.79410362]], dtype=float32),
 array([ 2.47543192,  1.08911276], dtype=float32),
 array([[ 8.60997963],
        [ 7.18411541]], dtype=float32),
 array([ 8.9881916], dtype=float32)]